# simulator/config.py
# ── Fill these in after running `cdk deploy` ──────────────────────────────────

# From CDK output: ShipmentTrackerStack.IoTEndpoint
IOT_ENDPOINT = "YOUR_IOT_ENDPOINT.iot.eu-central-1.amazonaws.com"

IOT_PORT = 8883

# Paths to certificates downloaded from AWS IoT Core console
# (or generated by CDK — see infrastructure/README)
CERT_PATH   = "certs/device-certificate.pem.crt"
KEY_PATH    = "certs/private.pem.key"
CA_PATH     = "certs/AmazonRootCA1.pem"

# IoT client identifier prefix
CLIENT_ID_PREFIX = "shipment-simulator"
