"""
Provision (or revoke) an AWS IoT device certificate for the GPS simulator.

The private key is generated by AWS IoT, written to simulator/certs/ and never
stored in CloudFormation. The certificate is attached to the least-privilege
policy created by the CDK stack (connect as shipment-simulator-*, publish to
shipments/*/location only).

Usage:
  python scripts/provision_device.py                 # create cert, write simulator/.env
  python scripts/provision_device.py --stage prod
  python scripts/provision_device.py --revoke        # detach + deactivate + delete
                                                     # (run before `cdk destroy`)
"""

import argparse
import sys
import urllib.request
from pathlib import Path

import boto3

ROOT      = Path(__file__).resolve().parent.parent
CERT_DIR  = ROOT / "simulator" / "certs"
ENV_FILE  = ROOT / "simulator" / ".env"
ROOT_CA   = "https://www.amazontrust.com/repository/AmazonRootCA1.pem"


def provision(iot, policy: str) -> None:
    CERT_DIR.mkdir(parents=True, exist_ok=True)
    if (CERT_DIR / "certificate-id.txt").exists():
        sys.exit(f"A certificate already exists in {CERT_DIR}. Run with --revoke first.")

    resp = iot.create_keys_and_certificate(setAsActive=True)
    iot.attach_policy(policyName=policy, target=resp["certificateArn"])

    (CERT_DIR / "device-certificate.pem.crt").write_text(resp["certificatePem"])
    key_path = CERT_DIR / "private.pem.key"
    key_path.write_text(resp["keyPair"]["PrivateKey"])
    try:
        key_path.chmod(0o600)
    except OSError:
        pass
    (CERT_DIR / "certificate-id.txt").write_text(resp["certificateId"])
    urllib.request.urlretrieve(ROOT_CA, CERT_DIR / "AmazonRootCA1.pem")

    endpoint = iot.describe_endpoint(endpointType="iot:Data-ATS")["endpointAddress"]
    ENV_FILE.write_text(f"IOT_ENDPOINT={endpoint}\n")

    print(f"Certificate {resp['certificateId'][:12]}… attached to {policy}")
    print(f"Certs written to {CERT_DIR}")
    print(f"IOT_ENDPOINT={endpoint}  (saved to {ENV_FILE})")


def revoke(iot, policy: str) -> None:
    id_file = CERT_DIR / "certificate-id.txt"
    if not id_file.exists():
        sys.exit("No provisioned certificate found.")
    cert_id  = id_file.read_text().strip()
    cert_arn = iot.describe_certificate(certificateId=cert_id)["certificateDescription"]["certificateArn"]

    iot.detach_policy(policyName=policy, target=cert_arn)
    iot.update_certificate(certificateId=cert_id, newStatus="INACTIVE")
    iot.delete_certificate(certificateId=cert_id, forceDelete=True)
    for f in CERT_DIR.glob("*"):
        f.unlink()
    print(f"Certificate {cert_id[:12]}… revoked and deleted.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--stage", default="dev")
    parser.add_argument("--region", default="eu-central-1")
    parser.add_argument("--revoke", action="store_true")
    args = parser.parse_args()

    client = boto3.client("iot", region_name=args.region)
    policy_name = f"ShipmentSimulatorPolicy-{args.stage}"
    (revoke if args.revoke else provision)(client, policy_name)
